"""whalebin: expose docker image binaries as host CLI commands.

Equivalent of `pixi global install` / `uv tool install` for docker images.
Uses Charliecloud (`ch-run`) as the container runtime: rootless, daemonless,
auto-mounts $HOME / $PWD / /tmp, so binaries inside the image behave as if
host-installed. Additional cluster paths (NFS subtrees, scratch volumes)
can be bound at install time via --mount.
"""
from __future__ import annotations

import argparse
import json
import os
import shlex
import shutil
import stat
import subprocess
import sys
import tomllib
from pathlib import Path

CONFIG_DIR = Path(os.environ.get("XDG_CONFIG_HOME", Path.home() / ".config")) / "whalebin"
BIN_DIR = Path(os.environ.get("WHALEBIN_BIN", Path.home() / ".local" / "bin"))
MANIFEST = CONFIG_DIR / "manifest.toml"
WRAPPER_MARK = "# generated by whalebin"
WRAPPER_HEADER = f"#!/usr/bin/env bash\n{WRAPPER_MARK}"
DEFAULT_MOUNTS: list[str] = []
CONTAINER_PATH = "/usr/local/bin:/usr/bin:/bin"


class WhalebinError(Exception):
    """Recoverable whalebin error; main() converts to a clean exit-1."""


def load_manifest() -> dict:
    if not MANIFEST.exists():
        return {"envs": {}}
    try:
        data = tomllib.loads(MANIFEST.read_text())
    except tomllib.TOMLDecodeError as e:
        raise WhalebinError(f"malformed manifest at {MANIFEST}: {e}")
    data.setdefault("envs", {})
    return data


def _toml_str_list(items: list[str]) -> str:
    return "[" + ", ".join(f'"{x}"' for x in items) + "]"


def save_manifest(data: dict) -> None:
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    lines: list[str] = []
    for name, cfg in sorted(data.get("envs", {}).items()):
        lines.append(f"[envs.{name}]")
        lines.append(f'image = "{cfg["image"]}"')
        lines.append(f"bins = {_toml_str_list(cfg['bins'])}")
        if cfg.get("mounts"):
            lines.append(f"mounts = {_toml_str_list(cfg['mounts'])}")
        lines.append("")
    MANIFEST.write_text("\n".join(lines))


def wrapper_content(env_name: str, image: str, bin_name: str, mounts: list[str]) -> str:
    bind_lines = "".join(f"    --bind {shlex.quote(m)} \\\n" for m in mounts)
    return f"""{WRAPPER_HEADER} (env: {env_name}, image: {image})
exec ch-run \\
    --unset-env=PATH --set-env="PATH={CONTAINER_PATH}" \\
    --cd "$PWD" \\
{bind_lines}    {shlex.quote(image)} -- \\
    {shlex.quote(bin_name)} "$@"
"""


def _ch_run_argv(image: str, bin_name: str, mounts: list[str], args: list[str]) -> list[str]:
    """Build ch-run argv equivalent to what the wrapper would exec, for `whalebin run`."""
    argv = ["ch-run", "--unset-env=PATH", f"--set-env=PATH={CONTAINER_PATH}",
            "--cd", os.getcwd()]
    for m in mounts:
        argv.extend(["--bind", m])
    argv.extend([image, "--", bin_name, *args])
    return argv


def _is_our_wrapper(path: Path) -> bool:
    if not path.exists():
        return False
    return path.read_text(errors="replace").startswith(WRAPPER_HEADER)


def _write_wrapper(path: Path, content: str) -> bool:
    """Write wrapper; return False if path is a foreign file (and skip)."""
    if path.exists() and not _is_our_wrapper(path):
        print(f"  skip (foreign file): {path}", file=sys.stderr)
        return False
    path.write_text(content)
    path.chmod(path.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)
    return True


def _install_wrapper(env_name: str, image: str, bin_name: str, mounts: list[str]) -> Path | None:
    """Write a wrapper for one bin; return the path on success, None if skipped."""
    BIN_DIR.mkdir(parents=True, exist_ok=True)
    path = BIN_DIR / bin_name
    if _write_wrapper(path, wrapper_content(env_name, image, bin_name, mounts)):
        return path
    return None


def _print_env_text(name: str, cfg: dict) -> None:
    print(name)
    print(f"  image:  {cfg['image']}")
    print(f"  bins:   {', '.join(cfg['bins'])}")
    if cfg.get("mounts"):
        print(f"  mounts: {', '.join(cfg['mounts'])}")


def _require_backend() -> None:
    for tool in ("ch-image", "ch-run"):
        if shutil.which(tool) is None:
            raise WhalebinError(f"{tool} not on PATH; install charliecloud "
                                 f"(see https://charliecloud.io/latest/install.html)")


def _run_checked(cmd: list[str], desc: str) -> None:
    try:
        subprocess.run(cmd, check=True)
    except subprocess.CalledProcessError as e:
        raise WhalebinError(f"{desc} failed (exit {e.returncode}): {' '.join(cmd)}")


def _acquire_image(image: str) -> None:
    """Import image into ch-image storage. Prefer local docker daemon over registry pull."""
    if shutil.which("docker") is not None:
        have = subprocess.run(
            ["docker", "image", "inspect", image],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
        )
        if have.returncode == 0:
            print(f"Importing {image} from local docker daemon ...")
            _run_checked(["ch-convert", "-i", "docker", "-o", "ch-image", image, image],
                         desc="ch-convert from docker")
            return
    print(f"Pulling {image} via ch-image ...")
    _run_checked(["ch-image", "pull", image], desc=f"ch-image pull {image}")


def _require_env(data: dict, name: str) -> dict:
    if name not in data["envs"]:
        raise WhalebinError(f"no such env: {name}")
    return data["envs"][name]


def cmd_install(args: argparse.Namespace) -> None:
    _require_backend()
    bins = [b.strip() for b in args.bin.split(",") if b.strip()]
    if not bins:
        raise WhalebinError("--bin must list at least one binary")
    mounts = args.mount if args.mount else list(DEFAULT_MOUNTS)

    data = load_manifest()
    if args.name in data["envs"]:
        print(f"note: replacing existing env '{args.name}'", file=sys.stderr)

    _acquire_image(args.image)

    written = 0
    for b in bins:
        path = _install_wrapper(args.name, args.image, b, mounts)
        if path:
            print(f"  installed: {path}")
            written += 1

    if written == 0:
        raise WhalebinError(f"no wrappers written for env '{args.name}' "
                             f"(every target shadowed by foreign files); manifest unchanged")

    data["envs"][args.name] = {"image": args.image, "bins": sorted(bins), "mounts": mounts}
    save_manifest(data)
    print(f"\nEnv '{args.name}' installed ({written}/{len(bins)} wrappers in {BIN_DIR}).")


def cmd_list(args: argparse.Namespace) -> None:
    envs = load_manifest()["envs"]
    if args.json:
        print(json.dumps(envs, indent=2, sort_keys=True))
        return
    if not envs:
        print("No environments installed.")
        return
    for name, cfg in sorted(envs.items()):
        _print_env_text(name, cfg)


def cmd_info(args: argparse.Namespace) -> None:
    data = load_manifest()
    cfg = _require_env(data, args.name)
    missing = [b for b in cfg["bins"] if not _is_our_wrapper(BIN_DIR / b)]
    if args.json:
        # Match `list --json` shape so scripts can parse uniformly.
        print(json.dumps({args.name: {**cfg, "missing_wrappers": missing}},
                         indent=2, sort_keys=True))
        return
    _print_env_text(args.name, cfg)
    if missing:
        print(f"  missing wrappers: {', '.join(missing)} "
              f"(run `whalebin sync` to regenerate)")


def cmd_uninstall(args: argparse.Namespace) -> None:
    _require_backend()
    data = load_manifest()
    cfg = _require_env(data, args.name)
    for b in cfg["bins"]:
        path = BIN_DIR / b
        if _is_our_wrapper(path):
            path.unlink()
            print(f"  removed: {path}")
    del data["envs"][args.name]
    save_manifest(data)
    if args.purge:
        print(f"Removing image {cfg['image']} from ch-image storage ...")
        subprocess.run(["ch-image", "delete", cfg["image"]], check=False)
    print(f"Env '{args.name}' uninstalled.")


def cmd_upgrade(args: argparse.Namespace) -> None:
    _require_backend()
    envs = load_manifest()["envs"]
    if args.all:
        targets = sorted(envs)
    else:
        if args.name not in envs:
            raise WhalebinError(f"no such env: {args.name}")
        targets = [args.name]
    if not targets:
        print("No environments to upgrade.")
        return
    failed: list[str] = []
    for name in targets:
        try:
            _acquire_image(envs[name]["image"])
        except WhalebinError as e:
            failed.append(name)
            print(f"  upgrade failed: {name}: {e}", file=sys.stderr)
    succeeded = len(targets) - len(failed)
    print(f"\nUpgraded {succeeded}/{len(targets)} env(s).")
    if failed:
        raise WhalebinError(f"upgrade failed for: {', '.join(failed)}")


def cmd_sync(args: argparse.Namespace) -> None:
    _require_backend()
    envs = load_manifest()["envs"]
    n = 0
    for name, cfg in envs.items():
        for b in cfg["bins"]:
            if _install_wrapper(name, cfg["image"], b, cfg.get("mounts", DEFAULT_MOUNTS)):
                n += 1
    print(f"Synced {n} wrappers from {MANIFEST}.")


def cmd_expose_add(args: argparse.Namespace) -> None:
    _require_backend()
    data = load_manifest()
    cfg = _require_env(data, args.env)
    if args.bin in cfg["bins"]:
        raise WhalebinError(f"'{args.bin}' already exposed in env '{args.env}'")
    path = BIN_DIR / args.bin
    if path.exists() and not _is_our_wrapper(path):
        raise WhalebinError(f"foreign file at {path}; refusing to overwrite")
    cfg["bins"] = sorted([*cfg["bins"], args.bin])
    written = _install_wrapper(args.env, cfg["image"], args.bin,
                                cfg.get("mounts", DEFAULT_MOUNTS))
    if not written:
        raise WhalebinError(f"failed to write {path}")
    save_manifest(data)
    print(f"exposed: {written}")


def cmd_expose_remove(args: argparse.Namespace) -> None:
    data = load_manifest()
    cfg = _require_env(data, args.env)
    if args.bin not in cfg["bins"]:
        raise WhalebinError(f"'{args.bin}' not exposed in env '{args.env}'")
    path = BIN_DIR / args.bin
    if _is_our_wrapper(path):
        path.unlink()
        print(f"removed: {path}")
    cfg["bins"].remove(args.bin)
    save_manifest(data)


def cmd_edit(args: argparse.Namespace) -> None:
    editor = os.environ.get("VISUAL") or os.environ.get("EDITOR") or "vi"
    if shutil.which(editor) is None:
        raise WhalebinError(f"editor not found on PATH: {editor} "
                             f"(check $VISUAL / $EDITOR)")
    CONFIG_DIR.mkdir(parents=True, exist_ok=True)
    if not MANIFEST.exists():
        MANIFEST.write_text("")
    rc = subprocess.run([editor, str(MANIFEST)]).returncode
    if rc != 0:
        raise WhalebinError(f"editor exited {rc}; manifest may not be saved")
    try:
        tomllib.loads(MANIFEST.read_text())
    except tomllib.TOMLDecodeError as e:
        raise WhalebinError(f"manifest at {MANIFEST} no longer valid TOML: {e}")
    print(f"manifest saved; run `whalebin sync` to regenerate wrappers.")


def cmd_run(args: argparse.Namespace) -> None:
    _require_backend()
    cfg = _require_env(load_manifest(), args.env)
    argv = _ch_run_argv(cfg["image"], args.bin,
                        cfg.get("mounts", DEFAULT_MOUNTS), args.args)
    os.execvp(argv[0], argv)


def main() -> None:
    p = argparse.ArgumentParser(prog="whalebin", description=__doc__.splitlines()[0])
    sub = p.add_subparsers(dest="cmd", required=True)

    pi = sub.add_parser("install", help="install a docker image as PATH binaries")
    pi.add_argument("name", help="local env name (e.g. texlive)")
    pi.add_argument("--image", required=True, help="docker image (e.g. texlive/texlive:latest-full)")
    pi.add_argument("--bin", required=True, help="comma-separated binary names to expose")
    pi.add_argument("--mount", action="append",
                    help="extra bind mount, repeatable (charliecloud auto-mounts $HOME/$PWD/$tmp)")
    pi.set_defaults(func=cmd_install)

    pl = sub.add_parser("list", help="list installed environments")
    pl.add_argument("--json", action="store_true", help="emit machine-readable JSON")
    pl.set_defaults(func=cmd_list)

    pin = sub.add_parser("info", help="show one env's details (including missing wrappers)")
    pin.add_argument("name")
    pin.add_argument("--json", action="store_true")
    pin.set_defaults(func=cmd_info)

    pu = sub.add_parser("uninstall", help="remove an env and its wrappers")
    pu.add_argument("name")
    pu.add_argument("--purge", action="store_true", help="also delete the image from ch-image storage")
    pu.set_defaults(func=cmd_uninstall)

    pup = sub.add_parser("upgrade", help="pull the latest image into ch-image storage")
    pup_target = pup.add_mutually_exclusive_group(required=True)
    pup_target.add_argument("name", nargs="?", default=None)
    pup_target.add_argument("--all", action="store_true")
    pup.set_defaults(func=cmd_upgrade)

    ps = sub.add_parser("sync", help="regenerate wrappers from manifest")
    ps.set_defaults(func=cmd_sync)

    pe = sub.add_parser("expose", help="add/remove a binary from an installed env")
    pe_sub = pe.add_subparsers(dest="expose_cmd", required=True)
    pea = pe_sub.add_parser("add", help="add a binary to an env (writes a new wrapper)")
    pea.add_argument("env")
    pea.add_argument("bin")
    pea.set_defaults(func=cmd_expose_add)
    per = pe_sub.add_parser("remove", help="remove a binary from an env (drops the wrapper)")
    per.add_argument("env")
    per.add_argument("bin")
    per.set_defaults(func=cmd_expose_remove)

    ped = sub.add_parser("edit", help="open the manifest in $EDITOR (then run `sync`)")
    ped.set_defaults(func=cmd_edit)

    pr = sub.add_parser("run", help="ephemeral run of a binary in an env (no wrapper needed)")
    pr.add_argument("env")
    pr.add_argument("bin")
    pr.add_argument("args", nargs=argparse.REMAINDER,
                    help="args forwarded to the binary (use -- to stop flag parsing)")
    pr.set_defaults(func=cmd_run)

    args = p.parse_args()
    try:
        args.func(args)
    except WhalebinError as e:
        sys.exit(f"error: {e}")


if __name__ == "__main__":
    main()
